### ISSUE TITLE
关于界面问题和整句翻译。

### ISSUE THREAD

**Issue by sunyuting83** [DreamSaddle/youdao-dict#1]
### 关于界面：可能是我主题的问题。单词翻译后字体看不清。
![01.jpg](https://p.pstatp.com/origin/feea0001c4eaeb7e45cc)
### 多点击闪退
- 英=>汉,输入单词点击翻译后。再切换 汉=>英 多点击几次翻译后会出现闪退现象。

**Comment by DreamSaddle** [comment]
**字体看不清：** 
造成这个问题的原因是我开发机器主题是黑色，我就设置了一个字体颜色为白色，昨天晚上我也发现了这个问题的，还没改，这个问题我后面就直接统一解决了 **将窗口背景设置为白色, 字体为黑色**，或者说有时间我研究一下适配主题

**无法整句翻译:**
目前是没有这个功能

**多点击闪退:**
这个问题我在开发时还没发现, 感谢提出:blush:，有空了我检查一下

**Comment by DreamSaddle** [comment]
我看了一下，整句翻译接口与单词翻译一致，这周末应该就可以弄好了。

**Comment by sunyuting83** [comment]
# 大佬加油！
