### ISSUE TITLE
含有特殊字符闪退的问题

### ISSUE THREAD

**Issue by sunyuting83** [DreamSaddle/youdao-dict#2]
无意中发现含有|符号会闪退。过滤掉特殊符号吧。

另外：大佬是否考虑发行arch的包？

**Comment by DreamSaddle** [comment]
> 无意中发现含有|符号会闪退。过滤掉特殊符号吧。
> 
> 另外：大佬是否考虑发行arch的包？

嗯，特殊字符可以过滤掉

周末吧，我打一下arch系列的包

**Comment by sunyuting83** [comment]
大佬，发现新问题。没有网络会闪退。要不要加层判断

**Comment by DreamSaddle** [comment]
> 大佬，发现新问题。没有网络会闪退。要不要加层判断

是没有网络时执行翻译操作会闪退吗?

**Comment by DreamSaddle** [comment]
> 大佬，发现新问题。没有网络会闪退。要不要加层判断

特殊符号和没网络闪退这两个问题,我先记录下,到时候统一修改发布

**Comment by sunyuting83** [comment]
好的。大佬辛苦了！
